# Generated by Django 3.0.3 on 2020-02-28 17:34

from django.db import migrations

    


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200228_1725'),
    ]

    operations = [
    ]
